--------------------------------------------------------------------------
-- Datos de prueba - Módulo de Compras + Inventario (script único, consolidado)
-- Oracle 21c
--
-- Une en un solo archivo los datos de prueba de:
--   1) Módulo de Compras (CMP_SOLICITUD_COMPRA, CMP_COTIZACION,
--      CMP_ORDEN_COMPRA, CMP_RECEPCION_BODEGA, CMP_FACTURA_CXP, etc.)
--   2) Módulo de Inventario (CMP_BODEGA, CMP_UBICACION, CMP_LOTE,
--      CMP_MOVIMIENTO_INVENTARIO, CMP_INVENTARIO, CMP_TOMA_FISICA)
--
-- Validado contra el DDL (db_analisis_ii.txt): nombres de tabla, columnas
-- y tipos de movimiento de inventario (REC_COMPRA, DEV_COMPRA, SAL_VENTA,
-- DEV_VENTA, TRF_SALIDA, TRF_ENTRADA, AJU_ENTRADA, AJU_SALIDA) coinciden
-- con lo ya sembrado por el propio DDL vía INSERT, por lo que aquí solo
-- se referencian por código (no se vuelven a insertar).
--
-- Requisito previo: haber corrido el DDL completo (crea tablas + siembra
-- catálogos base como CMP_TIPO_MOVIMIENTO_INV).
-- Ejecutar sobre tablas vacías/truncadas, de una sola vez, en este orden.
--------------------------------------------------------------------------

SET DEFINE OFF;

--------------------------------------------------------------------------
-- PARTE 0: LIMPIEZA PREVIA
--   Borra únicamente los datos de prueba que este script inserta más
--   abajo (respetando el orden de las FK: primero hijas, luego padres),
--   para poder re-ejecutar el archivo completo las veces que sea
--   necesario sin errores de llave duplicada ni de integridad referencial.
--
--   NO se borra "CMP_TIPO_MOVIMIENTO_INV": ese catálogo lo siembra el
--   propio DDL (db_analisis_ii.txt), no este script de datos de prueba.
--------------------------------------------------------------------------

DELETE FROM "CMP_BITACORA_AUDITORIA";
DELETE FROM "CMP_DETALLE_TOMA_FISICA";
DELETE FROM "CMP_TOMA_FISICA";
DELETE FROM "CMP_DETALLE_MOVIMIENTO_INV";
DELETE FROM "CMP_MOVIMIENTO_INVENTARIO";
DELETE FROM "CMP_INVENTARIO";
DELETE FROM "CMP_FACTURA_CXP";
DELETE FROM "CMP_DETALLE_RECEPCION";
DELETE FROM "CMP_RECEPCION_BODEGA";
DELETE FROM "CMP_DETALLE_ORDEN_COMPRA";
DELETE FROM "CMP_ORDEN_COMPRA";
DELETE FROM "CMP_COTIZACION";
DELETE FROM "CMP_DETALLE_SOLICITUD";
DELETE FROM "CMP_SOLICITUD_COMPRA";
DELETE FROM "CMP_LOTE";
DELETE FROM "CMP_UBICACION";
DELETE FROM "CMP_BODEGA";
DELETE FROM "CMP_ARTICULO";
DELETE FROM "CMP_UNIDAD_MEDIDA";
DELETE FROM "CMP_MARCA";
DELETE FROM "CMP_CATEGORIA";
DELETE FROM "CMP_ESTADO";
DELETE FROM "PROVEEDOR";
DELETE FROM "USUARIO";
DELETE FROM "DEPARTAMENTO";
DELETE FROM "CXC_SUCURSALES";
DELETE FROM "CXC_EMPRESAS";

COMMIT;

--------------------------------------------------------------------------
-- PARTE A: MÓDULO DE COMPRAS
--------------------------------------------------------------------------

-- 0. Tablas relacionadas (USUARIO, DEPARTAMENTO, PROVEEDOR)
INSERT INTO "DEPARTAMENTO" ("DEP_ID_DEPARTAMENTO", "DEP_NOMBRE_DEPARTAMENTO", "DEP_PRESUPUESTO_DISPONIBLE", "DEP_ACTIVO")
VALUES (1, 'Compras', 50000.00, 1);
INSERT INTO "DEPARTAMENTO" ("DEP_ID_DEPARTAMENTO", "DEP_NOMBRE_DEPARTAMENTO", "DEP_PRESUPUESTO_DISPONIBLE", "DEP_ACTIVO")
VALUES (2, 'Bodega / Logística', 20000.00, 1);

INSERT INTO "USUARIO" ("USU_ID_USUARIO", "USU_NOMBRE_COMPLETO", "USU_ID_DEPARTAMENTO", "USU_ACTIVO")
VALUES (1, 'Ana López', 1, 1);
INSERT INTO "USUARIO" ("USU_ID_USUARIO", "USU_NOMBRE_COMPLETO", "USU_ID_DEPARTAMENTO", "USU_ACTIVO")
VALUES (2, 'Luis Ramírez', 1, 1);
INSERT INTO "USUARIO" ("USU_ID_USUARIO", "USU_NOMBRE_COMPLETO", "USU_ID_DEPARTAMENTO", "USU_ACTIVO")
VALUES (3, 'Marta Girón', 2, 1);

INSERT INTO "PROVEEDOR" ("PRO_ID_PROVEEDOR", "PRO_NIT", "PRO_NOMBRE_ENTIDAD", "PRO_ACTIVO")
VALUES (1, '12345-6', 'Suministros Industriales S.A.', 1);
INSERT INTO "PROVEEDOR" ("PRO_ID_PROVEEDOR", "PRO_NIT", "PRO_NOMBRE_ENTIDAD", "PRO_ACTIVO")
VALUES (2, '98765-4', 'Tecnología y Cómputo GT', 1);
INSERT INTO "PROVEEDOR" ("PRO_ID_PROVEEDOR", "PRO_NIT", "PRO_NOMBRE_ENTIDAD", "PRO_ACTIVO")
VALUES (3, '55555-0', 'Mobiliario Corporativo', 1);

-- 1. Catálogos del módulo de compras
INSERT INTO "CMP_ESTADO" ("EST_ID_ESTADO", "EST_NOMBRE_ESTADO") VALUES (1, 'PENDIENTE');
INSERT INTO "CMP_ESTADO" ("EST_ID_ESTADO", "EST_NOMBRE_ESTADO") VALUES (2, 'APROBADA');
INSERT INTO "CMP_ESTADO" ("EST_ID_ESTADO", "EST_NOMBRE_ESTADO") VALUES (3, 'EN_PROCESO');
INSERT INTO "CMP_ESTADO" ("EST_ID_ESTADO", "EST_NOMBRE_ESTADO") VALUES (4, 'RECIBIDA');
INSERT INTO "CMP_ESTADO" ("EST_ID_ESTADO", "EST_NOMBRE_ESTADO") VALUES (5, 'CERRADA');

INSERT INTO "CMP_CATEGORIA" ("CAT_ID_CATEGORIA", "CAT_NOMBRE_CATEGORIA") VALUES (1, 'Suministros de oficina');
INSERT INTO "CMP_CATEGORIA" ("CAT_ID_CATEGORIA", "CAT_NOMBRE_CATEGORIA") VALUES (2, 'Equipo de cómputo');
INSERT INTO "CMP_CATEGORIA" ("CAT_ID_CATEGORIA", "CAT_NOMBRE_CATEGORIA") VALUES (3, 'Mobiliario');

INSERT INTO "CMP_MARCA" ("MAR_ID_MARCA", "MAR_NOMBRE_MARCA") VALUES (1, 'HP');
INSERT INTO "CMP_MARCA" ("MAR_ID_MARCA", "MAR_NOMBRE_MARCA") VALUES (2, 'Genérica');
INSERT INTO "CMP_MARCA" ("MAR_ID_MARCA", "MAR_NOMBRE_MARCA") VALUES (3, 'Herman Miller');

INSERT INTO "CMP_UNIDAD_MEDIDA" ("UME_ID_UNIDAD", "UME_NOMBRE_UNIDAD", "UME_ABREVIATURA") VALUES (1, 'Unidad', 'UND');
INSERT INTO "CMP_UNIDAD_MEDIDA" ("UME_ID_UNIDAD", "UME_NOMBRE_UNIDAD", "UME_ABREVIATURA") VALUES (2, 'Caja', 'CJA');
INSERT INTO "CMP_UNIDAD_MEDIDA" ("UME_ID_UNIDAD", "UME_NOMBRE_UNIDAD", "UME_ABREVIATURA") VALUES (3, 'Resma', 'RSM');

INSERT INTO "CMP_ARTICULO" ("ART_CODIGO_ARTICULO", "ART_DESCRIPCION", "ART_ID_CATEGORIA", "ART_ID_MARCA", "ART_ID_UNIDAD_COMPRA", "ART_ID_UNIDAD_VENTA")
VALUES ('ART-0001', 'Laptop HP 14" 8GB/256GB', 2, 1, 1, 1);
INSERT INTO "CMP_ARTICULO" ("ART_CODIGO_ARTICULO", "ART_DESCRIPCION", "ART_ID_CATEGORIA", "ART_ID_MARCA", "ART_ID_UNIDAD_COMPRA", "ART_ID_UNIDAD_VENTA")
VALUES ('ART-0002', 'Resma de papel bond carta', 1, 2, 3, 3);
INSERT INTO "CMP_ARTICULO" ("ART_CODIGO_ARTICULO", "ART_DESCRIPCION", "ART_ID_CATEGORIA", "ART_ID_MARCA", "ART_ID_UNIDAD_COMPRA", "ART_ID_UNIDAD_VENTA")
VALUES ('ART-0003', 'Silla ergonómica de oficina', 3, 3, 1, 1);
INSERT INTO "CMP_ARTICULO" ("ART_CODIGO_ARTICULO", "ART_DESCRIPCION", "ART_ID_CATEGORIA", "ART_ID_MARCA", "ART_ID_UNIDAD_COMPRA", "ART_ID_UNIDAD_VENTA")
VALUES ('ART-0004', 'Tóner HP negro original', 1, 1, 1, 1);
INSERT INTO "CMP_ARTICULO" ("ART_CODIGO_ARTICULO", "ART_DESCRIPCION", "ART_ID_CATEGORIA", "ART_ID_MARCA", "ART_ID_UNIDAD_COMPRA", "ART_ID_UNIDAD_VENTA")
VALUES ('ART-0005', 'Mouse inalámbrico', 2, 2, 2, 1);

-- 2. Flujo completo x 5 ejemplos
-- ===== Ejemplo 1: Laptops =====
INSERT INTO "CMP_SOLICITUD_COMPRA" ("SOL_NO_DOCUMENTO", "SOL_ID_USUARIO_RESPONSABLE", "SOL_ID_DEPARTAMENTO", "SOL_NOTAS", "SOL_MONTO_TOTAL_ESTIMADO", "SOL_ID_ESTADO")
VALUES ('SOL-2026-0001', 1, 1, 'Renovación de equipo de cómputo', 12000.00, 2);
INSERT INTO "CMP_DETALLE_SOLICITUD" ("DSO_ID_DETALLE_SOLICITUD", "DSO_NO_DOCUMENTO_SOLICITUD", "DSO_CODIGO_ARTICULO", "DSO_CANTIDAD_PEDIDA", "DSO_CANTIDAD_APROBADA")
VALUES (1, 'SOL-2026-0001', 'ART-0001', 2, 2);
INSERT INTO "CMP_COTIZACION" ("COT_ID_COTIZACION", "COT_NO_DOCUMENTO_SOLICITUD", "COT_ID_PROVEEDOR", "COT_PRECIO_TOTAL", "COT_TIEMPO_ENTREGA_DIAS", "COT_CONDICION_PAGO_DIAS", "COT_ESTADO_ADJUDICACION")
VALUES (1, 'SOL-2026-0001', 2, 11800.00, 5, 30, 'GANADORA');
INSERT INTO "CMP_ORDEN_COMPRA" ("OCO_NO_PO", "OCO_ID_COTIZACION_GANADORA", "OCO_SUBTOTAL", "OCO_MONTO_IVA", "OCO_TOTAL", "OCO_ID_ESTADO")
VALUES ('PO-2026-0001', 1, 10535.71, 1264.29, 11800.00, 3);
INSERT INTO "CMP_DETALLE_ORDEN_COMPRA" ("DOC_ID_DETALLE_PO", "DOC_NO_PO", "DOC_CODIGO_ARTICULO", "DOC_CANTIDAD_PEDIDA", "DOC_PRECIO_UNITARIO", "DOC_TOTAL_LINEA")
VALUES (1, 'PO-2026-0001', 'ART-0001', 2, 5900.00, 11800.00);
INSERT INTO "CMP_RECEPCION_BODEGA" ("RBO_NO_RECEPCION", "RBO_NO_PO", "RBO_ID_USUARIO_BODEGA", "RBO_TIPO_RECEPCION", "RBO_SUBTOTAL_RECIBIDO", "RBO_IVA_RECIBIDO", "RBO_TOTAL_FACTURAR")
VALUES ('REC-2026-0001', 'PO-2026-0001', 3, 'COMPLETA', 10535.71, 1264.29, 11800.00);
INSERT INTO "CMP_DETALLE_RECEPCION" ("DRE_ID_DETALLE_RECEPCION", "DRE_NO_RECEPCION", "DRE_CODIGO_ARTICULO", "DRE_CANTIDAD_RECIBIDA", "DRE_VERIFICADO_FISICAMENTE")
VALUES (1, 'REC-2026-0001', 'ART-0001', 2, 1);
INSERT INTO "CMP_FACTURA_CXP" ("FAC_NO_FACTURA", "FAC_ID_PROVEEDOR", "FAC_NO_PO", "FAC_NO_RECEPCION", "FAC_FECHA_FACTURA", "FAC_SUBTOTAL", "FAC_MONTO_IVA", "FAC_TOTAL_FACTURA", "FAC_ID_ESTADO")
VALUES ('FAC-2026-0001', 2, 'PO-2026-0001', 'REC-2026-0001', DATE '2026-08-10', 10535.71, 1264.29, 11800.00, 4);

-- ===== Ejemplo 2: Papelería =====
INSERT INTO "CMP_SOLICITUD_COMPRA" ("SOL_NO_DOCUMENTO", "SOL_ID_USUARIO_RESPONSABLE", "SOL_ID_DEPARTAMENTO", "SOL_NOTAS", "SOL_MONTO_TOTAL_ESTIMADO", "SOL_ID_ESTADO")
VALUES ('SOL-2026-0002', 2, 1, 'Reabastecimiento de papelería trimestral', 900.00, 2);
INSERT INTO "CMP_DETALLE_SOLICITUD" ("DSO_ID_DETALLE_SOLICITUD", "DSO_NO_DOCUMENTO_SOLICITUD", "DSO_CODIGO_ARTICULO", "DSO_CANTIDAD_PEDIDA", "DSO_CANTIDAD_APROBADA")
VALUES (2, 'SOL-2026-0002', 'ART-0002', 50, 50);
INSERT INTO "CMP_COTIZACION" ("COT_ID_COTIZACION", "COT_NO_DOCUMENTO_SOLICITUD", "COT_ID_PROVEEDOR", "COT_PRECIO_TOTAL", "COT_TIEMPO_ENTREGA_DIAS", "COT_CONDICION_PAGO_DIAS", "COT_ES_EXCEPCION_UNICO", "COT_ESTADO_ADJUDICACION")
VALUES (2, 'SOL-2026-0002', 1, 850.00, 2, 15, 0, 'GANADORA');
INSERT INTO "CMP_ORDEN_COMPRA" ("OCO_NO_PO", "OCO_ID_COTIZACION_GANADORA", "OCO_SUBTOTAL", "OCO_MONTO_IVA", "OCO_TOTAL", "OCO_ID_ESTADO")
VALUES ('PO-2026-0002', 2, 758.93, 91.07, 850.00, 3);
INSERT INTO "CMP_DETALLE_ORDEN_COMPRA" ("DOC_ID_DETALLE_PO", "DOC_NO_PO", "DOC_CODIGO_ARTICULO", "DOC_CANTIDAD_PEDIDA", "DOC_PRECIO_UNITARIO", "DOC_TOTAL_LINEA")
VALUES (2, 'PO-2026-0002', 'ART-0002', 50, 17.00, 850.00);
INSERT INTO "CMP_RECEPCION_BODEGA" ("RBO_NO_RECEPCION", "RBO_NO_PO", "RBO_ID_USUARIO_BODEGA", "RBO_TIPO_RECEPCION", "RBO_SUBTOTAL_RECIBIDO", "RBO_IVA_RECIBIDO", "RBO_TOTAL_FACTURAR")
VALUES ('REC-2026-0002', 'PO-2026-0002', 3, 'COMPLETA', 758.93, 91.07, 850.00);
INSERT INTO "CMP_DETALLE_RECEPCION" ("DRE_ID_DETALLE_RECEPCION", "DRE_NO_RECEPCION", "DRE_CODIGO_ARTICULO", "DRE_CANTIDAD_RECIBIDA", "DRE_VERIFICADO_FISICAMENTE")
VALUES (2, 'REC-2026-0002', 'ART-0002', 50, 1);
INSERT INTO "CMP_FACTURA_CXP" ("FAC_NO_FACTURA", "FAC_ID_PROVEEDOR", "FAC_NO_PO", "FAC_NO_RECEPCION", "FAC_FECHA_FACTURA", "FAC_SUBTOTAL", "FAC_MONTO_IVA", "FAC_TOTAL_FACTURA", "FAC_ID_ESTADO")
VALUES ('FAC-2026-0002', 1, 'PO-2026-0002', 'REC-2026-0002', DATE '2026-08-12', 758.93, 91.07, 850.00, 4);

-- ===== Ejemplo 3: Mobiliario (recepción parcial, sin facturar) =====
INSERT INTO "CMP_SOLICITUD_COMPRA" ("SOL_NO_DOCUMENTO", "SOL_ID_USUARIO_RESPONSABLE", "SOL_ID_DEPARTAMENTO", "SOL_NOTAS", "SOL_MONTO_TOTAL_ESTIMADO", "SOL_ID_ESTADO")
VALUES ('SOL-2026-0003', 1, 1, 'Sillas ergonómicas para nuevo personal', 3600.00, 2);
INSERT INTO "CMP_DETALLE_SOLICITUD" ("DSO_ID_DETALLE_SOLICITUD", "DSO_NO_DOCUMENTO_SOLICITUD", "DSO_CODIGO_ARTICULO", "DSO_CANTIDAD_PEDIDA", "DSO_CANTIDAD_APROBADA")
VALUES (3, 'SOL-2026-0003', 'ART-0003', 4, 4);
INSERT INTO "CMP_COTIZACION" ("COT_ID_COTIZACION", "COT_NO_DOCUMENTO_SOLICITUD", "COT_ID_PROVEEDOR", "COT_PRECIO_TOTAL", "COT_TIEMPO_ENTREGA_DIAS", "COT_CONDICION_PAGO_DIAS", "COT_ESTADO_ADJUDICACION")
VALUES (3, 'SOL-2026-0003', 3, 3600.00, 10, 45, 'GANADORA');
INSERT INTO "CMP_ORDEN_COMPRA" ("OCO_NO_PO", "OCO_ID_COTIZACION_GANADORA", "OCO_SUBTOTAL", "OCO_MONTO_IVA", "OCO_TOTAL", "OCO_ID_ESTADO")
VALUES ('PO-2026-0003', 3, 3214.29, 385.71, 3600.00, 3);
INSERT INTO "CMP_DETALLE_ORDEN_COMPRA" ("DOC_ID_DETALLE_PO", "DOC_NO_PO", "DOC_CODIGO_ARTICULO", "DOC_CANTIDAD_PEDIDA", "DOC_PRECIO_UNITARIO", "DOC_TOTAL_LINEA")
VALUES (3, 'PO-2026-0003', 'ART-0003', 4, 900.00, 3600.00);
INSERT INTO "CMP_RECEPCION_BODEGA" ("RBO_NO_RECEPCION", "RBO_NO_PO", "RBO_ID_USUARIO_BODEGA", "RBO_TIPO_RECEPCION", "RBO_SUBTOTAL_RECIBIDO", "RBO_IVA_RECIBIDO", "RBO_TOTAL_FACTURAR")
VALUES ('REC-2026-0003', 'PO-2026-0003', 3, 'PARCIAL', 1607.14, 192.86, 1800.00);
INSERT INTO "CMP_DETALLE_RECEPCION" ("DRE_ID_DETALLE_RECEPCION", "DRE_NO_RECEPCION", "DRE_CODIGO_ARTICULO", "DRE_CANTIDAD_RECIBIDA", "DRE_VERIFICADO_FISICAMENTE")
VALUES (3, 'REC-2026-0003', 'ART-0003', 2, 1);

-- ===== Ejemplo 4: Tóner, compra por excepción a proveedor único =====
INSERT INTO "CMP_SOLICITUD_COMPRA" ("SOL_NO_DOCUMENTO", "SOL_ID_USUARIO_RESPONSABLE", "SOL_ID_DEPARTAMENTO", "SOL_NOTAS", "SOL_MONTO_TOTAL_ESTIMADO", "SOL_ID_ESTADO")
VALUES ('SOL-2026-0004', 2, 1, 'Tóner agotado, compra urgente a proveedor único', 480.00, 2);
INSERT INTO "CMP_DETALLE_SOLICITUD" ("DSO_ID_DETALLE_SOLICITUD", "DSO_NO_DOCUMENTO_SOLICITUD", "DSO_CODIGO_ARTICULO", "DSO_CANTIDAD_PEDIDA", "DSO_CANTIDAD_APROBADA")
VALUES (4, 'SOL-2026-0004', 'ART-0004', 6, 6);
INSERT INTO "CMP_COTIZACION" ("COT_ID_COTIZACION", "COT_NO_DOCUMENTO_SOLICITUD", "COT_ID_PROVEEDOR", "COT_PRECIO_TOTAL", "COT_TIEMPO_ENTREGA_DIAS", "COT_CONDICION_PAGO_DIAS", "COT_ES_EXCEPCION_UNICO", "COT_ESTADO_ADJUDICACION")
VALUES (4, 'SOL-2026-0004', 2, 480.00, 1, 0, 1, 'GANADORA');
INSERT INTO "CMP_ORDEN_COMPRA" ("OCO_NO_PO", "OCO_ID_COTIZACION_GANADORA", "OCO_SUBTOTAL", "OCO_MONTO_IVA", "OCO_TOTAL", "OCO_ID_ESTADO")
VALUES ('PO-2026-0004', 4, 428.57, 51.43, 480.00, 4);
INSERT INTO "CMP_DETALLE_ORDEN_COMPRA" ("DOC_ID_DETALLE_PO", "DOC_NO_PO", "DOC_CODIGO_ARTICULO", "DOC_CANTIDAD_PEDIDA", "DOC_PRECIO_UNITARIO", "DOC_TOTAL_LINEA")
VALUES (4, 'PO-2026-0004', 'ART-0004', 6, 80.00, 480.00);
INSERT INTO "CMP_RECEPCION_BODEGA" ("RBO_NO_RECEPCION", "RBO_NO_PO", "RBO_ID_USUARIO_BODEGA", "RBO_TIPO_RECEPCION", "RBO_SUBTOTAL_RECIBIDO", "RBO_IVA_RECIBIDO", "RBO_TOTAL_FACTURAR")
VALUES ('REC-2026-0004', 'PO-2026-0004', 3, 'COMPLETA', 428.57, 51.43, 480.00);
INSERT INTO "CMP_DETALLE_RECEPCION" ("DRE_ID_DETALLE_RECEPCION", "DRE_NO_RECEPCION", "DRE_CODIGO_ARTICULO", "DRE_CANTIDAD_RECIBIDA", "DRE_VERIFICADO_FISICAMENTE")
VALUES (4, 'REC-2026-0004', 'ART-0004', 6, 1);
INSERT INTO "CMP_FACTURA_CXP" ("FAC_NO_FACTURA", "FAC_ID_PROVEEDOR", "FAC_NO_PO", "FAC_NO_RECEPCION", "FAC_FECHA_FACTURA", "FAC_SUBTOTAL", "FAC_MONTO_IVA", "FAC_TOTAL_FACTURA", "FAC_RUTA_ARCHIVO_PDF", "FAC_ID_ESTADO")
VALUES ('FAC-2026-0003', 2, 'PO-2026-0004', 'REC-2026-0004', DATE '2026-08-20', 428.57, 51.43, 480.00, '/facturas/2026/FAC-2026-0003.pdf', 5);

-- ===== Ejemplo 5: Mouse, solicitud pendiente (sin cotización/orden/recepción/factura) =====
INSERT INTO "CMP_SOLICITUD_COMPRA" ("SOL_NO_DOCUMENTO", "SOL_ID_USUARIO_RESPONSABLE", "SOL_ID_DEPARTAMENTO", "SOL_NOTAS", "SOL_MONTO_TOTAL_ESTIMADO", "SOL_ID_ESTADO")
VALUES ('SOL-2026-0005', 1, 1, 'Reposición de periféricos', 300.00, 1);
INSERT INTO "CMP_DETALLE_SOLICITUD" ("DSO_ID_DETALLE_SOLICITUD", "DSO_NO_DOCUMENTO_SOLICITUD", "DSO_CODIGO_ARTICULO", "DSO_CANTIDAD_PEDIDA")
VALUES (5, 'SOL-2026-0005', 'ART-0005', 10);

-- Bitácora de auditoría
INSERT INTO "CMP_BITACORA_AUDITORIA" ("BIT_ID_BITACORA", "BIT_ID_USUARIO", "BIT_DIRECCION_IP_ORIGEN", "BIT_ACCION", "BIT_VALORES_PREVIOS", "BIT_VALORES_POSTERIORES")
VALUES (1, 1, '192.168.1.10', 'APROBACION_SOLICITUD', 'SOL_ID_ESTADO=1', 'SOL_ID_ESTADO=2');
INSERT INTO "CMP_BITACORA_AUDITORIA" ("BIT_ID_BITACORA", "BIT_ID_USUARIO", "BIT_DIRECCION_IP_ORIGEN", "BIT_ACCION", "BIT_VALORES_PREVIOS", "BIT_VALORES_POSTERIORES")
VALUES (2, 3, '192.168.1.25', 'RECEPCION_PARCIAL', 'DRE_CANTIDAD_RECIBIDA=0', 'DRE_CANTIDAD_RECIBIDA=2');

--------------------------------------------------------------------------
-- PARTE B: MÓDULO DE INVENTARIO
--   (usa los tipos de movimiento ya sembrados por el DDL vía MERGE:
--    REC_COMPRA, DEV_COMPRA, SAL_VENTA, DEV_VENTA, TRF_SALIDA,
--    TRF_ENTRADA, AJU_ENTRADA, AJU_SALIDA — se referencian por código,
--    NO se vuelven a insertar)
--------------------------------------------------------------------------

-- 1. Empresa / sucursal (requeridas por CMP_BODEGA)
INSERT INTO "CXC_EMPRESAS" ("ID_EMPRESA", "NOMBRE", "NIT")
VALUES (1, 'Empresa Ejemplo, S.A.', '1234567-8');
INSERT INTO "CXC_SUCURSALES" ("ID_SUCURSAL", "ID_EMPRESA", "NOMBRE", "DIRECCION")
VALUES (1, 1, 'Sucursal Central', 'Zona 4, Ciudad de Guatemala');

-- 2. Bodegas y ubicaciones
INSERT INTO "CMP_BODEGA" ("BOD_ID_BODEGA", "BOD_CODIGO", "BOD_NOMBRE", "BOD_ID_SUCURSAL", "BOD_DIRECCION")
VALUES (1, 'BOD-01', 'Bodega Central', 1, 'Zona 4, Ciudad de Guatemala');
INSERT INTO "CMP_BODEGA" ("BOD_ID_BODEGA", "BOD_CODIGO", "BOD_NOMBRE", "BOD_ID_SUCURSAL", "BOD_DIRECCION")
VALUES (2, 'BOD-02', 'Bodega Secundaria', 1, 'Zona 12, Ciudad de Guatemala');

INSERT INTO "CMP_UBICACION" ("UBI_ID_UBICACION", "UBI_ID_BODEGA", "UBI_CODIGO_UBICACION", "UBI_PASILLO", "UBI_RACK", "UBI_NIVEL")
VALUES (1, 1, 'A-01-01', 'A', '01', '01');
INSERT INTO "CMP_UBICACION" ("UBI_ID_UBICACION", "UBI_ID_BODEGA", "UBI_CODIGO_UBICACION", "UBI_PASILLO", "UBI_RACK", "UBI_NIVEL")
VALUES (2, 1, 'A-01-02', 'A', '01', '02');
INSERT INTO "CMP_UBICACION" ("UBI_ID_UBICACION", "UBI_ID_BODEGA", "UBI_CODIGO_UBICACION", "UBI_PASILLO", "UBI_RACK", "UBI_NIVEL")
VALUES (3, 2, 'B-01-01', 'B', '01', '01');

-- 3. Lote
INSERT INTO "CMP_LOTE" ("LOT_ID_LOTE", "LOT_NUMERO_LOTE", "LOT_CODIGO_ARTICULO", "LOT_FECHA_PRODUCCION", "LOT_FECHA_VENCIMIENTO")
VALUES (1, 'LOTE-2026-001', 'ART-0004', DATE '2026-01-15', DATE '2027-01-15');

-- 4. Movimientos de inventario (7 movimientos: 2 entradas por compra,
--    1 venta, 1 traslado -en dos filas, salida/entrada-, 2 ajustes por toma física)
INSERT INTO "CMP_MOVIMIENTO_INVENTARIO" ("MIN_ID_MOVIMIENTO", "MIN_NUMERO_MOVIMIENTO", "MIN_ID_TIPO_MOVIMIENTO", "MIN_ID_BODEGA_ORIGEN", "MIN_NO_RECEPCION_ORIGEN", "MIN_ID_USUARIO", "MIN_ESTADO")
VALUES (1, 'MOV-2026-0001',
        (SELECT "TMI_ID_TIPO_MOVIMIENTO" FROM "CMP_TIPO_MOVIMIENTO_INV" WHERE "TMI_CODIGO" = 'REC_COMPRA'),
        1, 'REC-2026-0001', 3, 'APLICADO');
INSERT INTO "CMP_DETALLE_MOVIMIENTO_INV" ("DMI_ID_DETALLE", "DMI_ID_MOVIMIENTO", "DMI_CODIGO_ARTICULO", "DMI_ID_UBICACION", "DMI_CANTIDAD", "DMI_COSTO_UNITARIO", "DMI_COSTO_TOTAL", "DMI_EXISTENCIA_PREVIA", "DMI_EXISTENCIA_POSTERIOR")
VALUES (1, 1, 'ART-0001', 1, 2, 5900.00, 11800.00, 0, 2);

INSERT INTO "CMP_MOVIMIENTO_INVENTARIO" ("MIN_ID_MOVIMIENTO", "MIN_NUMERO_MOVIMIENTO", "MIN_ID_TIPO_MOVIMIENTO", "MIN_ID_BODEGA_ORIGEN", "MIN_NO_RECEPCION_ORIGEN", "MIN_ID_USUARIO", "MIN_ESTADO")
VALUES (2, 'MOV-2026-0002',
        (SELECT "TMI_ID_TIPO_MOVIMIENTO" FROM "CMP_TIPO_MOVIMIENTO_INV" WHERE "TMI_CODIGO" = 'REC_COMPRA'),
        1, 'REC-2026-0002', 3, 'APLICADO');
INSERT INTO "CMP_DETALLE_MOVIMIENTO_INV" ("DMI_ID_DETALLE", "DMI_ID_MOVIMIENTO", "DMI_CODIGO_ARTICULO", "DMI_ID_UBICACION", "DMI_CANTIDAD", "DMI_COSTO_UNITARIO", "DMI_COSTO_TOTAL", "DMI_EXISTENCIA_PREVIA", "DMI_EXISTENCIA_POSTERIOR")
VALUES (2, 2, 'ART-0002', 1, 50, 17.00, 850.00, 0, 50);

INSERT INTO "CMP_MOVIMIENTO_INVENTARIO" ("MIN_ID_MOVIMIENTO", "MIN_NUMERO_MOVIMIENTO", "MIN_ID_TIPO_MOVIMIENTO", "MIN_ID_BODEGA_ORIGEN", "MIN_REFERENCIA_EXTERNA", "MIN_ID_USUARIO", "MIN_ESTADO")
VALUES (3, 'MOV-2026-0003',
        (SELECT "TMI_ID_TIPO_MOVIMIENTO" FROM "CMP_TIPO_MOVIMIENTO_INV" WHERE "TMI_CODIGO" = 'SAL_VENTA'),
        1, 'FACT-VTA-00456', 2, 'APLICADO');
INSERT INTO "CMP_DETALLE_MOVIMIENTO_INV" ("DMI_ID_DETALLE", "DMI_ID_MOVIMIENTO", "DMI_CODIGO_ARTICULO", "DMI_ID_UBICACION", "DMI_CANTIDAD", "DMI_COSTO_UNITARIO", "DMI_COSTO_TOTAL", "DMI_EXISTENCIA_PREVIA", "DMI_EXISTENCIA_POSTERIOR")
VALUES (3, 3, 'ART-0002', 1, 3, 17.00, 51.00, 50, 47);

INSERT INTO "CMP_MOVIMIENTO_INVENTARIO" ("MIN_ID_MOVIMIENTO", "MIN_NUMERO_MOVIMIENTO", "MIN_ID_TIPO_MOVIMIENTO", "MIN_ID_BODEGA_ORIGEN", "MIN_ID_BODEGA_DESTINO", "MIN_ID_USUARIO", "MIN_ESTADO", "MIN_OBSERVACIONES")
VALUES (4, 'MOV-2026-0004',
        (SELECT "TMI_ID_TIPO_MOVIMIENTO" FROM "CMP_TIPO_MOVIMIENTO_INV" WHERE "TMI_CODIGO" = 'TRF_SALIDA'),
        1, 2, 3, 'APLICADO', 'Salida por traslado a bodega secundaria');
INSERT INTO "CMP_DETALLE_MOVIMIENTO_INV" ("DMI_ID_DETALLE", "DMI_ID_MOVIMIENTO", "DMI_CODIGO_ARTICULO", "DMI_ID_UBICACION", "DMI_CANTIDAD", "DMI_COSTO_UNITARIO", "DMI_COSTO_TOTAL", "DMI_EXISTENCIA_PREVIA", "DMI_EXISTENCIA_POSTERIOR")
VALUES (4, 4, 'ART-0001', 1, 1, 5900.00, 5900.00, 2, 1);

INSERT INTO "CMP_MOVIMIENTO_INVENTARIO" ("MIN_ID_MOVIMIENTO", "MIN_NUMERO_MOVIMIENTO", "MIN_ID_TIPO_MOVIMIENTO", "MIN_ID_BODEGA_ORIGEN", "MIN_ID_BODEGA_DESTINO", "MIN_ID_USUARIO", "MIN_ESTADO", "MIN_OBSERVACIONES")
VALUES (5, 'MOV-2026-0005',
        (SELECT "TMI_ID_TIPO_MOVIMIENTO" FROM "CMP_TIPO_MOVIMIENTO_INV" WHERE "TMI_CODIGO" = 'TRF_ENTRADA'),
        2, 1, 3, 'APLICADO', 'Entrada por traslado desde bodega central');
INSERT INTO "CMP_DETALLE_MOVIMIENTO_INV" ("DMI_ID_DETALLE", "DMI_ID_MOVIMIENTO", "DMI_CODIGO_ARTICULO", "DMI_ID_UBICACION", "DMI_CANTIDAD", "DMI_COSTO_UNITARIO", "DMI_COSTO_TOTAL", "DMI_EXISTENCIA_PREVIA", "DMI_EXISTENCIA_POSTERIOR")
VALUES (5, 5, 'ART-0001', 3, 1, 5900.00, 5900.00, 0, 1);

INSERT INTO "CMP_MOVIMIENTO_INVENTARIO" ("MIN_ID_MOVIMIENTO", "MIN_NUMERO_MOVIMIENTO", "MIN_ID_TIPO_MOVIMIENTO", "MIN_ID_BODEGA_ORIGEN", "MIN_ID_USUARIO", "MIN_ESTADO", "MIN_OBSERVACIONES")
VALUES (6, 'MOV-2026-0006',
        (SELECT "TMI_ID_TIPO_MOVIMIENTO" FROM "CMP_TIPO_MOVIMIENTO_INV" WHERE "TMI_CODIGO" = 'AJU_ENTRADA'),
        1, 1, 'APLICADO', 'Ajuste generado por toma física TOM-2026-0001');
INSERT INTO "CMP_DETALLE_MOVIMIENTO_INV" ("DMI_ID_DETALLE", "DMI_ID_MOVIMIENTO", "DMI_CODIGO_ARTICULO", "DMI_ID_UBICACION", "DMI_CANTIDAD", "DMI_COSTO_UNITARIO", "DMI_COSTO_TOTAL", "DMI_EXISTENCIA_PREVIA", "DMI_EXISTENCIA_POSTERIOR")
VALUES (6, 6, 'ART-0005', 1, 1, 45.00, 45.00, 0, 1);

INSERT INTO "CMP_MOVIMIENTO_INVENTARIO" ("MIN_ID_MOVIMIENTO", "MIN_NUMERO_MOVIMIENTO", "MIN_ID_TIPO_MOVIMIENTO", "MIN_ID_BODEGA_ORIGEN", "MIN_ID_USUARIO", "MIN_ESTADO", "MIN_OBSERVACIONES")
VALUES (7, 'MOV-2026-0007',
        (SELECT "TMI_ID_TIPO_MOVIMIENTO" FROM "CMP_TIPO_MOVIMIENTO_INV" WHERE "TMI_CODIGO" = 'AJU_SALIDA'),
        1, 1, 'APLICADO', 'Ajuste generado por toma física TOM-2026-0001');
INSERT INTO "CMP_DETALLE_MOVIMIENTO_INV" ("DMI_ID_DETALLE", "DMI_ID_MOVIMIENTO", "DMI_CODIGO_ARTICULO", "DMI_ID_UBICACION", "DMI_CANTIDAD", "DMI_COSTO_UNITARIO", "DMI_COSTO_TOTAL", "DMI_EXISTENCIA_PREVIA", "DMI_EXISTENCIA_POSTERIOR")
VALUES (7, 7, 'ART-0002', 1, 2, 17.00, 34.00, 47, 45);

-- 5. Existencias resultantes (snapshot de CMP_INVENTARIO)
INSERT INTO "CMP_INVENTARIO" ("INV_ID_INVENTARIO", "INV_ID_BODEGA", "INV_CODIGO_ARTICULO", "INV_ID_UBICACION_DEFECTO", "INV_EXISTENCIA_ACTUAL", "INV_STOCK_DISPONIBLE", "INV_STOCK_MINIMO", "INV_STOCK_MAXIMO", "INV_PUNTO_REORDEN", "INV_COSTO_PROMEDIO_LOCAL", "INV_ULTIMO_COSTO_COMPRA", "INV_FECHA_ULTIMO_MOVIMIENTO")
VALUES (1, 1, 'ART-0001', 1, 1, 1, 1, 10, 2, 5900.00, 5900.00, SYSTIMESTAMP);
INSERT INTO "CMP_INVENTARIO" ("INV_ID_INVENTARIO", "INV_ID_BODEGA", "INV_CODIGO_ARTICULO", "INV_ID_UBICACION_DEFECTO", "INV_EXISTENCIA_ACTUAL", "INV_STOCK_DISPONIBLE", "INV_STOCK_MINIMO", "INV_STOCK_MAXIMO", "INV_PUNTO_REORDEN", "INV_COSTO_PROMEDIO_LOCAL", "INV_ULTIMO_COSTO_COMPRA", "INV_FECHA_ULTIMO_MOVIMIENTO")
VALUES (2, 1, 'ART-0002', 1, 45, 45, 10, 200, 20, 17.00, 17.00, SYSTIMESTAMP);
INSERT INTO "CMP_INVENTARIO" ("INV_ID_INVENTARIO", "INV_ID_BODEGA", "INV_CODIGO_ARTICULO", "INV_ID_UBICACION_DEFECTO", "INV_EXISTENCIA_ACTUAL", "INV_STOCK_DISPONIBLE", "INV_STOCK_MINIMO", "INV_STOCK_MAXIMO", "INV_PUNTO_REORDEN", "INV_COSTO_PROMEDIO_LOCAL", "INV_ULTIMO_COSTO_COMPRA", "INV_FECHA_ULTIMO_MOVIMIENTO")
VALUES (3, 1, 'ART-0003', 2, 2, 2, 1, 10, 2, 900.00, 900.00, SYSTIMESTAMP);
INSERT INTO "CMP_INVENTARIO" ("INV_ID_INVENTARIO", "INV_ID_BODEGA", "INV_CODIGO_ARTICULO", "INV_ID_UBICACION_DEFECTO", "INV_EXISTENCIA_ACTUAL", "INV_STOCK_DISPONIBLE", "INV_STOCK_MINIMO", "INV_STOCK_MAXIMO", "INV_PUNTO_REORDEN", "INV_COSTO_PROMEDIO_LOCAL", "INV_ULTIMO_COSTO_COMPRA", "INV_FECHA_ULTIMO_MOVIMIENTO")
VALUES (4, 1, 'ART-0004', 2, 6, 6, 2, 20, 4, 80.00, 80.00, SYSTIMESTAMP);
INSERT INTO "CMP_INVENTARIO" ("INV_ID_INVENTARIO", "INV_ID_BODEGA", "INV_CODIGO_ARTICULO", "INV_ID_UBICACION_DEFECTO", "INV_EXISTENCIA_ACTUAL", "INV_STOCK_DISPONIBLE", "INV_STOCK_MINIMO", "INV_STOCK_MAXIMO", "INV_PUNTO_REORDEN", "INV_COSTO_PROMEDIO_LOCAL", "INV_ULTIMO_COSTO_COMPRA", "INV_FECHA_ULTIMO_MOVIMIENTO")
VALUES (5, 1, 'ART-0005', 1, 1, 1, 1, 15, 3, 45.00, 45.00, SYSTIMESTAMP);
INSERT INTO "CMP_INVENTARIO" ("INV_ID_INVENTARIO", "INV_ID_BODEGA", "INV_CODIGO_ARTICULO", "INV_ID_UBICACION_DEFECTO", "INV_EXISTENCIA_ACTUAL", "INV_STOCK_DISPONIBLE", "INV_STOCK_MINIMO", "INV_STOCK_MAXIMO", "INV_PUNTO_REORDEN", "INV_COSTO_PROMEDIO_LOCAL", "INV_ULTIMO_COSTO_COMPRA", "INV_FECHA_ULTIMO_MOVIMIENTO")
VALUES (6, 2, 'ART-0001', 3, 1, 1, 0, 5, 1, 5900.00, 5900.00, SYSTIMESTAMP);

-- 6. Toma física
INSERT INTO "CMP_TOMA_FISICA" ("TOM_ID_TOMA", "TOM_NUMERO_TOMA", "TOM_ID_BODEGA", "TOM_FECHA_TOMA", "TOM_ESTADO", "TOM_ID_USUARIO_CREA", "TOM_ID_USUARIO_CIERRA", "TOM_FECHA_CIERRE", "TOM_OBSERVACIONES")
VALUES (1, 'TOM-2026-0001', 1, DATE '2026-08-31', 'AJUSTADA', 3, 1, TIMESTAMP '2026-09-01 09:00:00', 'Conteo mensual de bodega central');

INSERT INTO "CMP_DETALLE_TOMA_FISICA" ("DTF_ID_DETALLE", "DTF_ID_TOMA", "DTF_CODIGO_ARTICULO", "DTF_ID_UBICACION", "DTF_STOCK_TEORICO", "DTF_STOCK_FISICO", "DTF_DIFERENCIA", "DTF_COSTO_UNITARIO", "DTF_COSTO_DIFERENCIA", "DTF_AJUSTADO")
VALUES (1, 1, 'ART-0005', 1, 0, 1, 1, 45.00, 45.00, 1);
INSERT INTO "CMP_DETALLE_TOMA_FISICA" ("DTF_ID_DETALLE", "DTF_ID_TOMA", "DTF_CODIGO_ARTICULO", "DTF_ID_UBICACION", "DTF_STOCK_TEORICO", "DTF_STOCK_FISICO", "DTF_DIFERENCIA", "DTF_COSTO_UNITARIO", "DTF_COSTO_DIFERENCIA", "DTF_AJUSTADO")
VALUES (2, 1, 'ART-0002', 1, 47, 45, -2, 17.00, -34.00, 1);

-- 7. Vincular las recepciones con la Bodega Central
UPDATE "CMP_RECEPCION_BODEGA"
   SET "RBO_ID_BODEGA" = 1
 WHERE "RBO_NO_RECEPCION" IN ('REC-2026-0001','REC-2026-0002','REC-2026-0003','REC-2026-0004');

COMMIT;
