-- =============================================================================
-- Índices — Dominio CxC
-- =============================================================================
-- Oracle NO indexa automáticamente las columnas de FOREIGN KEY. Todas las
-- consultas del módulo (repositories/**) hacen JOIN o WHERE sobre estas
-- columnas en listados paginados, así que quedan indexadas explícitamente.
-- Se agregan además índices compuestos para los filtros/orden más usados en
-- SELECT_BASE de cada repositorio (estado + fecha de listados).
-- =============================================================================

PROMPT Creando índices...

-- CXC_SUCURSALES
CREATE INDEX IX_CXC_SUCURSALES_EMPRESA ON CXC_SUCURSALES (ID_EMPRESA);

-- CXC_RUTAS
CREATE INDEX IX_CXC_RUTAS_EMPLEADO ON CXC_RUTAS (ID_EMPLEADO);

-- CXC_RUTA_DETALLE
CREATE INDEX IX_CXC_RD_RUTA ON CXC_RUTA_DETALLE (ID_RUTA);
CREATE INDEX IX_CXC_RD_CLIENTE ON CXC_RUTA_DETALLE (ID_CLIENTE);

-- CXC_DOCUMENTOS (findAll ordena por FECHA_DOCUMENTO DESC, ID_DOCUMENTO DESC;
-- catalogos.repository filtra por ID_CLIENTE + SALDO > 0 + ESTADO)
CREATE INDEX IX_CXC_DOC_CLIENTE ON CXC_DOCUMENTOS (ID_CLIENTE);
CREATE INDEX IX_CXC_DOC_TIPO ON CXC_DOCUMENTOS (ID_TIPO_DOCUMENTO);
CREATE INDEX IX_CXC_DOC_MONEDA ON CXC_DOCUMENTOS (ID_MONEDA);
CREATE INDEX IX_CXC_DOC_CONDICION ON CXC_DOCUMENTOS (ID_CONDICION_CREDITO);
CREATE INDEX IX_CXC_DOC_ANULACION ON CXC_DOCUMENTOS (ID_EMPLEADO_ANULACION);
CREATE INDEX IX_CXC_DOC_CLIENTE_SALDO ON CXC_DOCUMENTOS (ID_CLIENTE, SALDO);
CREATE INDEX IX_CXC_DOC_FECHA ON CXC_DOCUMENTOS (FECHA_DOCUMENTO DESC, ID_DOCUMENTO DESC);

-- CXC_DOCUMENTO_DETALLE
CREATE INDEX IX_CXC_DD_DOCUMENTO ON CXC_DOCUMENTO_DETALLE (ID_DOCUMENTO);

-- CXC_DOCUMENTO_HISTORIAL
CREATE INDEX IX_CXC_DH_DOCUMENTO ON CXC_DOCUMENTO_HISTORIAL (ID_DOCUMENTO);
CREATE INDEX IX_CXC_DH_EMPLEADO ON CXC_DOCUMENTO_HISTORIAL (ID_EMPLEADO);

-- CXC_GESTIONES_COBRO (findAll ordena por FECHA_GESTION DESC, ID_GESTION DESC)
CREATE INDEX IX_CXC_GC_CLIENTE ON CXC_GESTIONES_COBRO (ID_CLIENTE);
CREATE INDEX IX_CXC_GC_DOCUMENTO ON CXC_GESTIONES_COBRO (ID_DOCUMENTO);
CREATE INDEX IX_CXC_GC_EMPLEADO ON CXC_GESTIONES_COBRO (ID_EMPLEADO);
CREATE INDEX IX_CXC_GC_FECHA ON CXC_GESTIONES_COBRO (FECHA_GESTION DESC, ID_GESTION DESC);

-- CXC_MORA (clienteElegibleParaConvenio filtra por ID_DOCUMENTO + ESTADO)
CREATE INDEX IX_CXC_MORA_DOCUMENTO ON CXC_MORA (ID_DOCUMENTO);
CREATE INDEX IX_CXC_MORA_ESTADO ON CXC_MORA (ESTADO);

-- CXC_AJUSTES
CREATE INDEX IX_CXC_AJ_CLIENTE ON CXC_AJUSTES (ID_CLIENTE);
CREATE INDEX IX_CXC_AJ_DOCUMENTO ON CXC_AJUSTES (ID_DOCUMENTO);
CREATE INDEX IX_CXC_AJ_EMPLEADO ON CXC_AJUSTES (ID_EMPLEADO);
CREATE INDEX IX_CXC_AJ_APROBADOR ON CXC_AJUSTES (ID_EMPLEADO_APROBADOR);

-- CXC_NOTAS_CREDITO (listNotasCreditoActivas agrupa/filtra por ESTADO)
CREATE INDEX IX_CXC_NC_CLIENTE ON CXC_NOTAS_CREDITO (ID_CLIENTE);
CREATE INDEX IX_CXC_NC_DOCUMENTO ON CXC_NOTAS_CREDITO (ID_DOCUMENTO_REFERENCIA);
CREATE INDEX IX_CXC_NC_ESTADO ON CXC_NOTAS_CREDITO (ESTADO);
CREATE INDEX IX_CXC_NC_ANULACION ON CXC_NOTAS_CREDITO (ID_EMPLEADO_ANULACION);

-- CXC_PAGOS
CREATE INDEX IX_CXC_PAGOS_CLIENTE ON CXC_PAGOS (ID_CLIENTE);
CREATE INDEX IX_CXC_PAGOS_FORMA ON CXC_PAGOS (ID_FORMA_PAGO);
CREATE INDEX IX_CXC_PAGOS_MONEDA ON CXC_PAGOS (ID_MONEDA);
CREATE INDEX IX_CXC_PAGOS_ESTADO ON CXC_PAGOS (ESTADO);
CREATE INDEX IX_CXC_PAGOS_ANULACION ON CXC_PAGOS (ID_EMPLEADO_ANULACION);

-- CXC_PROMESAS_PAGO (findAll ordena por FECHA_PROMESA DESC, ID_PROMESA DESC;
-- clienteElegibleParaConvenio filtra por ID_CLIENTE + ESTADO)
CREATE INDEX IX_CXC_PP_CLIENTE ON CXC_PROMESAS_PAGO (ID_CLIENTE);
CREATE INDEX IX_CXC_PP_DOCUMENTO ON CXC_PROMESAS_PAGO (ID_DOCUMENTO);
CREATE INDEX IX_CXC_PP_GESTION ON CXC_PROMESAS_PAGO (ID_GESTION);
CREATE INDEX IX_CXC_PP_CLIENTE_ESTADO ON CXC_PROMESAS_PAGO (ID_CLIENTE, ESTADO);

-- CXC_CONVENIOS_PAGO
CREATE INDEX IX_CXC_CV_CLIENTE ON CXC_CONVENIOS_PAGO (ID_CLIENTE);

-- CXC_APLICACION_NOTA_CREDITO
CREATE INDEX IX_CXC_ANC_NOTA ON CXC_APLICACION_NOTA_CREDITO (ID_NOTA_CREDITO);
CREATE INDEX IX_CXC_ANC_DOCUMENTO ON CXC_APLICACION_NOTA_CREDITO (ID_DOCUMENTO);
CREATE INDEX IX_CXC_ANC_ESTADO ON CXC_APLICACION_NOTA_CREDITO (ESTADO);
CREATE INDEX IX_CXC_ANC_REVERSA ON CXC_APLICACION_NOTA_CREDITO (ID_EMPLEADO_REVERSA);

-- CXC_APLICACION_PAGOS
CREATE INDEX IX_CXC_AP_PAGO ON CXC_APLICACION_PAGOS (ID_PAGO);
CREATE INDEX IX_CXC_AP_DOCUMENTO ON CXC_APLICACION_PAGOS (ID_DOCUMENTO);
CREATE INDEX IX_CXC_AP_EMPLEADO ON CXC_APLICACION_PAGOS (ID_EMPLEADO);
CREATE INDEX IX_CXC_AP_ESTADO ON CXC_APLICACION_PAGOS (ESTADO);
CREATE INDEX IX_CXC_AP_REVERSA ON CXC_APLICACION_PAGOS (ID_EMPLEADO_REVERSA);

-- CXC_ANTICIPOS
CREATE INDEX IX_CXC_ANT_CLIENTE ON CXC_ANTICIPOS (ID_CLIENTE);
CREATE INDEX IX_CXC_ANT_PAGO ON CXC_ANTICIPOS (ID_PAGO);

-- CXC_APLICACION_ANTICIPO
CREATE INDEX IX_CXC_AA_ANTICIPO ON CXC_APLICACION_ANTICIPO (ID_ANTICIPO);
CREATE INDEX IX_CXC_AA_DOCUMENTO ON CXC_APLICACION_ANTICIPO (ID_DOCUMENTO);
CREATE INDEX IX_CXC_AA_ESTADO ON CXC_APLICACION_ANTICIPO (ESTADO);
CREATE INDEX IX_CXC_AA_REVERSA ON CXC_APLICACION_ANTICIPO (ID_EMPLEADO_REVERSA);

-- CXC_RECIBOS
CREATE INDEX IX_CXC_REC_CLIENTE ON CXC_RECIBOS (ID_CLIENTE);
CREATE INDEX IX_CXC_REC_PAGO ON CXC_RECIBOS (ID_PAGO);

-- CXC_CONVENIO_CUOTAS (findByConvenio ordena por NUMERO_CUOTA; ya cubierto por
-- el UNIQUE(ID_CONVENIO, NUMERO_CUOTA) del DDL, que crea índice implícito)
CREATE INDEX IX_CXC_CC_FORMA_PAGO ON CXC_CONVENIO_CUOTAS (ID_FORMA_PAGO);

PROMPT Índices de CxC creados correctamente.
