-- =============================================================================
-- MIGRACIÓN — reversas, anulaciones, aprobación de ajustes, mora automática
-- y aplicación de anticipos.
-- =============================================================================
-- Este script se corre UNA VEZ contra el schema PROYECTOANALISIS que ya
-- tienes desplegado (el que compartiste). Es aditivo: solo ALTER TABLE ADD y
-- CREATE TABLE para lo que falta. No hace DROP ni MODIFY destructivo de
-- ninguna columna existente, así que es seguro correrlo aunque ya haya datos.
--
-- Motivo: el schema real fue desplegado antes de que esta sesión agregara
-- reversa de aplicaciones, anulación formal de pagos/NC/documentos,
-- aprobación de ajustes, el motor de mora automática (requiere
-- ID_CONDICION_CREDITO en CXC_DOCUMENTOS) y la aplicación de anticipos
-- (requiere la tabla CXC_APLICACION_ANTICIPO, que no existe todavía).
-- Sin este script, el código del server falla con ORA-00904 (columna no
-- existe) u ORA-00942 (tabla no existe) en esas rutas específicas; el resto
-- de la app (todo lo que ya tenías) sigue funcionando igual.
--
-- Orden de ejecución: de arriba hacia abajo (respeta dependencias de FK).
-- =============================================================================

PROMPT Migración CxC — reversas/anulaciones/mora/anticipo: iniciando...

--------------------------------------------------------
-- 1. CXC_DOCUMENTOS: condición de crédito (mora automática) + anulación
--------------------------------------------------------

ALTER TABLE "PROYECTOANALISIS"."CXC_DOCUMENTOS"
  ADD ("ID_CONDICION_CREDITO" NUMBER);

ALTER TABLE "PROYECTOANALISIS"."CXC_DOCUMENTOS"
  ADD CONSTRAINT "FK_CXC_DOC_CONDICION"
  FOREIGN KEY ("ID_CONDICION_CREDITO")
  REFERENCES "PROYECTOANALISIS"."CXC_CONDICIONES_CREDITO" ("ID_CONDICION");

CREATE INDEX "PROYECTOANALISIS"."IX_CXC_DOC_CONDICION"
  ON "PROYECTOANALISIS"."CXC_DOCUMENTOS" ("ID_CONDICION_CREDITO") TABLESPACE "USERS";

ALTER TABLE "PROYECTOANALISIS"."CXC_DOCUMENTOS"
  ADD ("ID_EMPLEADO_ANULACION" NUMBER, "FECHA_ANULACION" DATE, "MOTIVO_ANULACION" VARCHAR2(250 BYTE));

ALTER TABLE "PROYECTOANALISIS"."CXC_DOCUMENTOS"
  ADD CONSTRAINT "FK_CXC_DOC_ANULACION"
  FOREIGN KEY ("ID_EMPLEADO_ANULACION")
  REFERENCES "PROYECTOANALISIS"."EMPLEADO" ("ID_EMPLEADO");

CREATE INDEX "PROYECTOANALISIS"."IX_CXC_DOC_ANULACION"
  ON "PROYECTOANALISIS"."CXC_DOCUMENTOS" ("ID_EMPLEADO_ANULACION") TABLESPACE "USERS";

-- El backend valida numeroDocumento hasta 50 caracteres (identifierSchema),
-- pero la columna real es VARCHAR2(30): un valor de 31-50 caracteres pasaba
-- la validación de la app y tronaba en Oracle con ORA-12899 crudo. Se
-- ensancha para que coincida con lo que el contrato ya promete al usuario.
ALTER TABLE "PROYECTOANALISIS"."CXC_DOCUMENTOS"
  MODIFY ("NUMERO_DOCUMENTO" VARCHAR2(50 BYTE));

PROMPT [1/7] CXC_DOCUMENTOS actualizado (condición de crédito + anulación).

--------------------------------------------------------
-- 2. CXC_AJUSTES: flujo de aprobación
--------------------------------------------------------

ALTER TABLE "PROYECTOANALISIS"."CXC_AJUSTES"
  ADD ("ID_EMPLEADO_APROBADOR" NUMBER, "FECHA_APROBACION" DATE, "MOTIVO_RECHAZO" VARCHAR2(250 BYTE));

ALTER TABLE "PROYECTOANALISIS"."CXC_AJUSTES"
  ADD CONSTRAINT "FK_CXC_AJ_APROBADOR"
  FOREIGN KEY ("ID_EMPLEADO_APROBADOR")
  REFERENCES "PROYECTOANALISIS"."EMPLEADO" ("ID_EMPLEADO");

CREATE INDEX "PROYECTOANALISIS"."IX_CXC_AJ_APROBADOR"
  ON "PROYECTOANALISIS"."CXC_AJUSTES" ("ID_EMPLEADO_APROBADOR") TABLESPACE "USERS";

-- El ESTADO ya existe (DEFAULT 'APLICADO' en tu script real). El código del
-- server siempre lo fuerza a 'PENDIENTE' de forma explícita al crear un
-- ajuste, así que el DEFAULT de la columna no se usa; no hace falta tocarlo.
-- 'PENDIENTE'/'APROBADO'/'RECHAZADO'/'ANULADO' caben sin problema en el
-- VARCHAR2(20) ya existente.

PROMPT [2/7] CXC_AJUSTES actualizado (aprobación de ajustes).

--------------------------------------------------------
-- 3. CXC_APLICACION_PAGOS: reversa con trazabilidad
--------------------------------------------------------

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_PAGOS"
  ADD ("ESTADO" VARCHAR2(10 BYTE) DEFAULT 'CONFIRMADA' NOT NULL,
       "ID_EMPLEADO_REVERSA" NUMBER,
       "FECHA_REVERSA" DATE,
       "MOTIVO_REVERSA" VARCHAR2(250 BYTE));

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_PAGOS"
  ADD CONSTRAINT "CK_CXC_AP_ESTADO" CHECK (ESTADO IN ('CONFIRMADA', 'REVERSADA'));

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_PAGOS"
  ADD CONSTRAINT "FK_CXC_AP_REVERSA"
  FOREIGN KEY ("ID_EMPLEADO_REVERSA")
  REFERENCES "PROYECTOANALISIS"."EMPLEADO" ("ID_EMPLEADO");

CREATE INDEX "PROYECTOANALISIS"."IX_CXC_AP_ESTADO"
  ON "PROYECTOANALISIS"."CXC_APLICACION_PAGOS" ("ESTADO") TABLESPACE "USERS";
CREATE INDEX "PROYECTOANALISIS"."IX_CXC_AP_REVERSA"
  ON "PROYECTOANALISIS"."CXC_APLICACION_PAGOS" ("ID_EMPLEADO_REVERSA") TABLESPACE "USERS";

PROMPT [3/7] CXC_APLICACION_PAGOS actualizado (reversa).

--------------------------------------------------------
-- 4. CXC_APLICACION_NOTA_CREDITO: reversa con trazabilidad
--------------------------------------------------------

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_NOTA_CREDITO"
  ADD ("ESTADO" VARCHAR2(10 BYTE) DEFAULT 'CONFIRMADA' NOT NULL,
       "ID_EMPLEADO_REVERSA" NUMBER,
       "FECHA_REVERSA" DATE,
       "MOTIVO_REVERSA" VARCHAR2(250 BYTE));

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_NOTA_CREDITO"
  ADD CONSTRAINT "CK_CXC_ANC_ESTADO" CHECK (ESTADO IN ('CONFIRMADA', 'REVERSADA'));

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_NOTA_CREDITO"
  ADD CONSTRAINT "FK_CXC_ANC_REVERSA"
  FOREIGN KEY ("ID_EMPLEADO_REVERSA")
  REFERENCES "PROYECTOANALISIS"."EMPLEADO" ("ID_EMPLEADO");

CREATE INDEX "PROYECTOANALISIS"."IX_CXC_ANC_ESTADO"
  ON "PROYECTOANALISIS"."CXC_APLICACION_NOTA_CREDITO" ("ESTADO") TABLESPACE "USERS";
CREATE INDEX "PROYECTOANALISIS"."IX_CXC_ANC_REVERSA"
  ON "PROYECTOANALISIS"."CXC_APLICACION_NOTA_CREDITO" ("ID_EMPLEADO_REVERSA") TABLESPACE "USERS";

PROMPT [4/7] CXC_APLICACION_NOTA_CREDITO actualizado (reversa).

--------------------------------------------------------
-- 5. CXC_PAGOS y CXC_NOTAS_CREDITO: anulación formal
--------------------------------------------------------

ALTER TABLE "PROYECTOANALISIS"."CXC_PAGOS"
  ADD ("ID_EMPLEADO_ANULACION" NUMBER, "FECHA_ANULACION" DATE, "MOTIVO_ANULACION" VARCHAR2(250 BYTE));

ALTER TABLE "PROYECTOANALISIS"."CXC_PAGOS"
  ADD CONSTRAINT "FK_CXC_PAGOS_ANULACION"
  FOREIGN KEY ("ID_EMPLEADO_ANULACION")
  REFERENCES "PROYECTOANALISIS"."EMPLEADO" ("ID_EMPLEADO");

CREATE INDEX "PROYECTOANALISIS"."IX_CXC_PAGOS_ANULACION"
  ON "PROYECTOANALISIS"."CXC_PAGOS" ("ID_EMPLEADO_ANULACION") TABLESPACE "USERS";

ALTER TABLE "PROYECTOANALISIS"."CXC_NOTAS_CREDITO"
  ADD ("ID_EMPLEADO_ANULACION" NUMBER, "FECHA_ANULACION" DATE, "MOTIVO_ANULACION" VARCHAR2(250 BYTE));

ALTER TABLE "PROYECTOANALISIS"."CXC_NOTAS_CREDITO"
  ADD CONSTRAINT "FK_CXC_NC_ANULACION"
  FOREIGN KEY ("ID_EMPLEADO_ANULACION")
  REFERENCES "PROYECTOANALISIS"."EMPLEADO" ("ID_EMPLEADO");

CREATE INDEX "PROYECTOANALISIS"."IX_CXC_NC_ANULACION"
  ON "PROYECTOANALISIS"."CXC_NOTAS_CREDITO" ("ID_EMPLEADO_ANULACION") TABLESPACE "USERS";

PROMPT [5/7] CXC_PAGOS y CXC_NOTAS_CREDITO actualizados (anulación).

--------------------------------------------------------
-- 6. CXC_APLICACION_ANTICIPO: tabla nueva completa (no existía)
--------------------------------------------------------

CREATE TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO"
   (	"ID_APLICACION_ANTICIPO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE,
	"ID_ANTICIPO" NUMBER,
	"ID_DOCUMENTO" NUMBER,
	"FECHA_APLICACION" DATE,
	"MONTO_APLICADO" NUMBER(14,2),
	"ESTADO" VARCHAR2(10 BYTE) DEFAULT 'CONFIRMADA' NOT NULL,
	"ID_EMPLEADO_REVERSA" NUMBER,
	"FECHA_REVERSA" DATE,
	"MOTIVO_REVERSA" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

-- ID_APLICACION_ANTICIPO es IDENTITY: Oracle ya la deja NOT NULL al crearla,
-- así que forzarla de nuevo lanza ORA-01442 (inofensivo, pero redundante).
ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO" MODIFY ("ID_ANTICIPO" NOT NULL ENABLE);
ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO" MODIFY ("ID_DOCUMENTO" NOT NULL ENABLE);
ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO" MODIFY ("FECHA_APLICACION" NOT NULL ENABLE);
ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO" MODIFY ("MONTO_APLICADO" NOT NULL ENABLE);

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO"
  ADD CONSTRAINT "PK_CXC_APLICACION_ANTICIPO" PRIMARY KEY ("ID_APLICACION_ANTICIPO") USING INDEX TABLESPACE "USERS" ENABLE;

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO"
  ADD CONSTRAINT "CK_CXC_AA_ESTADO" CHECK (ESTADO IN ('CONFIRMADA', 'REVERSADA'));

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO"
  ADD CONSTRAINT "FK_CXC_AA_ANTICIPO"
  FOREIGN KEY ("ID_ANTICIPO") REFERENCES "PROYECTOANALISIS"."CXC_ANTICIPOS" ("ID_ANTICIPO");

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO"
  ADD CONSTRAINT "FK_CXC_AA_DOCUMENTO"
  FOREIGN KEY ("ID_DOCUMENTO") REFERENCES "PROYECTOANALISIS"."CXC_DOCUMENTOS" ("ID_DOCUMENTO");

ALTER TABLE "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO"
  ADD CONSTRAINT "FK_CXC_AA_REVERSA"
  FOREIGN KEY ("ID_EMPLEADO_REVERSA") REFERENCES "PROYECTOANALISIS"."EMPLEADO" ("ID_EMPLEADO");

CREATE INDEX "PROYECTOANALISIS"."IX_CXC_AA_ANTICIPO" ON "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO" ("ID_ANTICIPO") TABLESPACE "USERS";
CREATE INDEX "PROYECTOANALISIS"."IX_CXC_AA_DOCUMENTO" ON "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO" ("ID_DOCUMENTO") TABLESPACE "USERS";
CREATE INDEX "PROYECTOANALISIS"."IX_CXC_AA_ESTADO" ON "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO" ("ESTADO") TABLESPACE "USERS";
CREATE INDEX "PROYECTOANALISIS"."IX_CXC_AA_REVERSA" ON "PROYECTOANALISIS"."CXC_APLICACION_ANTICIPO" ("ID_EMPLEADO_REVERSA") TABLESPACE "USERS";

PROMPT [6/7] CXC_APLICACION_ANTICIPO creada.

--------------------------------------------------------
-- 7. Verificación rápida
--------------------------------------------------------
-- Corre esto después para confirmar que todo quedó bien (debe devolver 8 filas,
-- porque CXC_DOCUMENTOS aporta 2 columnas nuevas):
--
-- SELECT TABLE_NAME, COLUMN_NAME FROM USER_TAB_COLUMNS
--  WHERE (TABLE_NAME = 'CXC_DOCUMENTOS' AND COLUMN_NAME IN ('ID_CONDICION_CREDITO','ID_EMPLEADO_ANULACION'))
--     OR (TABLE_NAME = 'CXC_AJUSTES' AND COLUMN_NAME = 'ID_EMPLEADO_APROBADOR')
--     OR (TABLE_NAME = 'CXC_APLICACION_PAGOS' AND COLUMN_NAME = 'ESTADO')
--     OR (TABLE_NAME = 'CXC_APLICACION_NOTA_CREDITO' AND COLUMN_NAME = 'ESTADO')
--     OR (TABLE_NAME = 'CXC_PAGOS' AND COLUMN_NAME = 'ID_EMPLEADO_ANULACION')
--     OR (TABLE_NAME = 'CXC_NOTAS_CREDITO' AND COLUMN_NAME = 'ID_EMPLEADO_ANULACION')
--     OR (TABLE_NAME = 'CXC_APLICACION_ANTICIPO' AND COLUMN_NAME = 'ID_APLICACION_ANTICIPO');

PROMPT [7/7] Migración CxC completada.
